name: Bug report
description: Report a clearly broken issue in osu! lite.
body:
  - type: markdown
    attributes:
      value: |
        **Please search for existing issues before opening a new one.**

        Provide logs if available. Log files can be found from the General settings section or the storage directory.

  - type: dropdown
    attributes:
      label: Type
      options:
        - Crash to desktop
        - Game behaviour
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    attributes:
      label: Build version or commit hash
